language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: "coastbusters"
    token:
      secure: SONAR_TOKEN

script: 
- ant build
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- sonar-scanner
