language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: "persongc-github"
    token:
      secure: SONAR_TOKEN
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
